enum AchievementRarity { common, rare, epic, legendary }

class Achievement {
  final String id;
  final String titleUa;
  final String titleEn;
  final String descriptionUa;
  final String descriptionEn;
  final AchievementRarity rarity;
  final String icon;

  const Achievement({
    required this.id,
    required this.titleUa,
    required this.titleEn,
    required this.descriptionUa,
    required this.descriptionEn,
    required this.rarity,
    required this.icon,
  });
}

const List<Achievement> allAchievements = [
  Achievement(
    id: 'first_step',
    titleUa: 'Перший крок',
    titleEn: 'First Step',
    descriptionUa: 'Зробіть перший депозит у скарбничку',
    descriptionEn: 'Make your first deposit to the savings vault',
    rarity: AchievementRarity.common,
    icon: '🎯',
  ),
  Achievement(
    id: 'cyber_saver_3',
    titleUa: 'Кібер-Заощаджувач',
    titleEn: 'Cyber Saver',
    descriptionUa: 'Утримуйте 3-денну серію депозитів',
    descriptionEn: 'Maintain a 3-day deposit streak',
    rarity: AchievementRarity.common,
    icon: '⚡',
  ),
  Achievement(
    id: 'neon_streak_7',
    titleUa: 'Неонова іскра',
    titleEn: 'Neon Spark',
    descriptionUa: 'Утримуйте 7-денну серію депозитів',
    descriptionEn: 'Maintain a 7-day deposit streak',
    rarity: AchievementRarity.rare,
    icon: '🔥',
  ),
  Achievement(
    id: 'golden_flame_14',
    titleUa: 'Золоте полум\'я',
    titleEn: 'Golden Flame',
    descriptionUa: 'Утримуйте 14-денну серію депозитів',
    descriptionEn: 'Maintain a 14-day deposit streak',
    rarity: AchievementRarity.epic,
    icon: '👑',
  ),
  Achievement(
    id: 'immortal_fire_30',
    titleUa: 'Безсмертний вогонь',
    titleEn: 'Immortal Fire',
    descriptionUa: 'Утримуйте 30-денну серію депозитів',
    descriptionEn: 'Maintain a 30-day deposit streak',
    rarity: AchievementRarity.legendary,
    icon: '🪐',
  ),
  Achievement(
    id: 'halfway_ps5',
    titleUa: 'Півдороги до PS5',
    titleEn: 'Halfway to PS5',
    descriptionUa: 'Накопичено 50% від суми для PlayStation 5',
    descriptionEn: 'Accumulated 50% of target amount for PlayStation 5',
    rarity: AchievementRarity.rare,
    icon: '🎮',
  ),
  Achievement(
    id: 'halfway_monitor',
    titleUa: 'Півдороги до Монітора',
    titleEn: 'Halfway to Monitor',
    descriptionUa: 'Накопичено 50% від суми для Gaming Monitor',
    descriptionEn: 'Accumulated 50% of target amount for Gaming Monitor',
    rarity: AchievementRarity.rare,
    icon: '🖥️',
  ),
  Achievement(
    id: 'ps5_acquired',
    titleUa: 'Легенда PlayStation',
    titleEn: 'PlayStation Legend',
    descriptionUa: 'Накопичено 100% суми для PlayStation 5',
    descriptionEn: 'Accumulated 100% of target amount for PlayStation 5',
    rarity: AchievementRarity.legendary,
    icon: '🌌',
  ),
  Achievement(
    id: 'monitor_acquired',
    titleUa: 'Абсолютний візуал',
    titleEn: 'Absolute Visual',
    descriptionUa: 'Накопичено 100% суми для Gaming Monitor',
    descriptionEn: 'Accumulated 100% of target amount for Gaming Monitor',
    rarity: AchievementRarity.legendary,
    icon: '🔮',
  ),
  Achievement(
    id: 'split_master',
    titleUa: 'Майстер Спліту',
    titleEn: 'Split Master',
    descriptionUa: 'Зробіть депозит з розподілом 50% на 50%',
    descriptionEn: 'Make a deposit with 50% to 50% allocation',
    rarity: AchievementRarity.common,
    icon: '⚖️',
  ),
  Achievement(
    id: 'laser_focus_a',
    titleUa: 'Фокус на консолі',
    titleEn: 'Console Focus',
    descriptionUa: 'Спрямуйте 100% депозиту на PlayStation 5',
    descriptionEn: 'Direct 100% of deposit to PlayStation 5',
    rarity: AchievementRarity.common,
    icon: '📐',
  ),
  Achievement(
    id: 'laser_focus_b',
    titleUa: 'Фокус на екрані',
    titleEn: 'Screen Focus',
    descriptionUa: 'Спрямуйте 100% депозиту на Gaming Monitor',
    descriptionEn: 'Direct 100% of deposit to Gaming Monitor',
    rarity: AchievementRarity.common,
    icon: '🔍',
  ),
  Achievement(
    id: 'freeze_shield',
    titleUa: 'Кріогенний щит',
    titleEn: 'Cryogenic Shield',
    descriptionUa: 'Використайте токен заморозки серії',
    descriptionEn: 'Use a streak freeze token',
    rarity: AchievementRarity.common,
    icon: '❄️',
  ),
  Achievement(
    id: 'xp_hoarder_1',
    titleUa: 'Зростаюча сила',
    titleEn: 'Rising Power',
    descriptionUa: 'Досягніть 5-го рівня XP',
    descriptionEn: 'Reach XP Level 5',
    rarity: AchievementRarity.rare,
    icon: '🧬',
  ),
  Achievement(
    id: 'xp_legend',
    titleUa: 'Кібер-Лорд',
    titleEn: 'Cyber Lord',
    descriptionUa: 'Досягніть 10-го рівня XP',
    descriptionEn: 'Reach XP Level 10',
    rarity: AchievementRarity.epic,
    icon: '🛸',
  ),
  Achievement(
    id: 'night_owl',
    titleUa: 'Нічна сова',
    titleEn: 'Night Owl',
    descriptionUa: 'Зробіть депозит між 12 ночі та 5 ранку',
    descriptionEn: 'Make a deposit between 12 AM and 5 AM',
    rarity: AchievementRarity.common,
    icon: '🦉',
  ),
  Achievement(
    id: 'centurion',
    titleUa: 'Центуріон',
    titleEn: 'Centurion',
    descriptionUa: 'Зробіть одноразовий депозит від 100 одиниць',
    descriptionEn: 'Make a single deposit of 100+ units',
    rarity: AchievementRarity.epic,
    icon: '🧱',
  ),
  Achievement(
    id: 'big_boss',
    titleUa: 'Кібер-біржовий магнат',
    titleEn: 'Cyber Exchange Magnate',
    descriptionUa: 'Накопичено сумарно понад 1000 одиниць',
    descriptionEn: 'Accumulated more than 1000 units in total',
    rarity: AchievementRarity.legendary,
    icon: '💎',
  ),
  Achievement(
    id: 'serial_investor',
    titleUa: 'Серійний Інвестор',
    titleEn: 'Serial Investor',
    descriptionUa: 'Зроблено 10 транзакцій',
    descriptionEn: 'Made 10 transactions',
    rarity: AchievementRarity.epic,
    icon: '💸',
  ),
  Achievement(
    id: 'analytics_master',
    titleUa: 'Майстер Аналітики',
    titleEn: 'Analytics Master',
    descriptionUa: 'Переглянув аналітику 5 разів',
    descriptionEn: 'Viewed analytics 5 times',
    rarity: AchievementRarity.common,
    icon: '📊',
  ),
  Achievement(
    id: 'gambling_hacker',
    titleUa: 'Азартний Хакер',
    titleEn: 'Gambling Hacker',
    descriptionUa: 'Використав Daily Spin 3 дні поспіль',
    descriptionEn: 'Used Daily Spin 3 days in a row',
    rarity: AchievementRarity.rare,
    icon: '🎰',
  ),
];
